#!/usr/bin/env node
/**
 * Generates webapp/src/content.generated.ts from the real course files
 * (the module_NN_* directories one level up) and patches modules 3-25's
 * tutorial.html with a "Read the Primary Sources" section, built from
 * docs-data.mjs.
 *
 * Run with: node scripts/generate-content.mjs
 * Re-run any time the course module files change. Never hand-edit
 * content.generated.ts — it is overwritten every run.
 */
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, extname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DOCS } from './docs-data.mjs';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const webappRoot = join(__dirname, '..');
const courseRoot = join(webappRoot, '..');

const MODULE_DIRS = readdirSync(courseRoot, { withFileTypes: true })
  .filter((d) => d.isDirectory() && /^module_\d\d_/.test(d.name))
  .map((d) => d.name)
  .sort();

if (MODULE_DIRS.length !== 25) {
  throw new Error(`Expected 25 module_NN_* directories, found ${MODULE_DIRS.length}`);
}

const LANG_BY_EXT = { '.js': 'javascript', '.html': 'html', '.css': 'css', '.json': 'json', '.sh': 'bash' };
const SKIP_TOP_DIRS = new Set(['icons', '.idea', 'demo', 'node_modules']);
const SKIP_FILES = new Set(['build.sh', 'tutorial.html']);

// Files ordered so the pedagogically central ones come first.
const PRIORITY = ['manifest.json', 'background.js', 'content.js', 'content.css', 'storage_manager.js', 'popup.js', 'popup.html', 'popup.css', 'options.js', 'options.html', 'options.css'];

function priorityRank(name) {
  const i = PRIORITY.indexOf(name);
  return i === -1 ? PRIORITY.length : i;
}

function collectFiles(moduleDir) {
  const abs = join(courseRoot, moduleDir);
  const out = [];

  function walk(rel) {
    const dirAbs = join(abs, rel);
    for (const entry of readdirSync(dirAbs, { withFileTypes: true })) {
      if (!rel && SKIP_TOP_DIRS.has(entry.name)) continue;
      const entryRel = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        // only descend into 'assets' (real page-world JS lives there); skip other subdirs
        if (entry.name === 'assets') walk(entryRel);
        continue;
      }
      if (SKIP_FILES.has(entry.name)) continue;
      const ext = extname(entry.name);
      const lang = LANG_BY_EXT[ext];
      if (!lang) continue;
      out.push({ name: entryRel, lang, code: readFileSync(join(dirAbs, entry.name), 'utf8') });
    }
  }

  walk('');
  out.sort((a, b) => priorityRank(a.name) - priorityRank(b.name) || a.name.localeCompare(b.name));
  return out;
}

const DECISION_HEADER_RE = /^## Decision (\d+): (.+)$/;

function parseDecisions(moduleDir) {
  const path = join(courseRoot, moduleDir, 'DECISIONS.md');
  const text = readFileSync(path, 'utf8');
  const lines = text.split('\n');

  const blocks = [];
  let current = null;
  for (const line of lines) {
    const m = line.match(DECISION_HEADER_RE);
    if (m) {
      if (current) blocks.push(current);
      current = { num: Number(m[1]), title: m[2].trim(), bodyLines: [] };
    } else if (current) {
      current.bodyLines.push(line);
    }
  }
  if (current) blocks.push(current);

  return blocks.map((b) => {
    const body = b.bodyLines.join('\n').trim();

    const decisionM = body.match(/\*\*Decision:\*\*\s*([\s\S]*?)(?=\n\n\*\*|$)/);
    const whyM = body.match(/\*\*Why:\*\*\s*([\s\S]*?)(?=\n\n\*\*|$)/);
    const tradeoffM = body.match(/\*\*Trade-off:\*\*\s*([\s\S]*?)(?=\n\n---|\n---|$)/);

    // Preserve paragraph/bullet structure (rendered as markdown-lite in the
    // webapp) instead of flattening to one line — most modules' decisions
    // (5-25) are full multi-paragraph/bulleted write-ups, not one-liners.
    const clean = (s) => s.replace(/^---\s*/, '').replace(/[ \t]+$/gm, '').trim();

    if (decisionM || whyM || tradeoffM) {
      return {
        num: b.num,
        title: b.title,
        decision: decisionM ? clean(decisionM[1]) : null,
        why: whyM ? clean(whyM[1]) : null,
        tradeoff: tradeoffM ? clean(tradeoffM[1]) : null,
      };
    }
    return { num: b.num, title: b.title, body: clean(body.replace(/\n+---\s*$/, '')) };
  });
}

function tsString(s) {
  return JSON.stringify(s);
}

function moduleNumFromDir(dir) {
  return Number(dir.match(/^module_(\d\d)_/)[1]);
}

const contentByNum = {};
for (const dir of MODULE_DIRS) {
  const num = moduleNumFromDir(dir);
  contentByNum[num] = {
    files: collectFiles(dir),
    decisions: parseDecisions(dir),
    docs: DOCS[num] ?? [],
  };
}

let out = '';
out += '// AUTO-GENERATED by scripts/generate-content.mjs — do not hand-edit.\n';
out += '// Re-run `node scripts/generate-content.mjs` after changing course module files.\n\n';
out += 'export interface FileEntry { name: string; lang: string; code: string }\n';
out += 'export interface DecisionEntry { num: number; title: string; decision?: string | null; why?: string | null; tradeoff?: string | null; body?: string }\n';
out += 'export interface DocLink { title: string; description: string; url: string }\n';
out += 'export interface ModuleContent { files: FileEntry[]; decisions: DecisionEntry[]; docs: DocLink[] }\n\n';
out += 'export const MODULE_CONTENT: Record<number, ModuleContent> = {\n';

for (const num of Object.keys(contentByNum).map(Number).sort((a, b) => a - b)) {
  const c = contentByNum[num];
  out += `  ${num}: {\n`;
  out += '    files: [\n';
  for (const f of c.files) {
    out += `      { name: ${tsString(f.name)}, lang: ${tsString(f.lang)}, code: ${tsString(f.code)} },\n`;
  }
  out += '    ],\n';
  out += '    decisions: [\n';
  for (const d of c.decisions) {
    if (d.body !== undefined) {
      out += `      { num: ${d.num}, title: ${tsString(d.title)}, body: ${tsString(d.body)} },\n`;
    } else {
      out += `      { num: ${d.num}, title: ${tsString(d.title)}, decision: ${d.decision ? tsString(d.decision) : 'null'}, why: ${d.why ? tsString(d.why) : 'null'}, tradeoff: ${d.tradeoff ? tsString(d.tradeoff) : 'null'} },\n`;
    }
  }
  out += '    ],\n';
  out += '    docs: [\n';
  for (const doc of c.docs) {
    out += `      { title: ${tsString(doc.title)}, description: ${tsString(doc.description)}, url: ${tsString(doc.url)} },\n`;
  }
  out += '    ],\n';
  out += '  },\n';
}
out += '};\n';

writeFileSync(join(webappRoot, 'src', 'content.generated.ts'), out, 'utf8');
console.log(`Wrote src/content.generated.ts (${MODULE_DIRS.length} modules)`);

// ── Patch modules 3-25's tutorial.html with a "Read the Primary Sources"
//    section, if it doesn't already have real spec-ref links (1-2 do). ──

const SPEC_REF_CSS = `
    /* ── Spec reference (added by generate-content.mjs) ────── */
    .gen-spec-ref {
      background: rgba(255, 255, 255, 0.03);
      border: 1px solid var(--border);
      border-radius: 8px;
      padding: 14px 18px;
      margin: 24px 0;
      font-size: 13.5px;
      display: flex;
      align-items: flex-start;
      gap: 12px;
    }
    .gen-spec-ref-icon { font-size: 18px; flex-shrink: 0; }
    .gen-spec-ref-body { color: var(--muted); line-height: 1.6; }
    .gen-spec-ref-body a { color: var(--cyan); }
`;

function buildSpecRefSection(num) {
  const docs = DOCS[num] ?? [];
  if (docs.length === 0) return '';
  const cards = docs
    .map(
      (d) => `  <div class="gen-spec-ref">
    <span class="gen-spec-ref-icon">\u{1F4C4}</span>
    <div class="gen-spec-ref-body">
      <strong>${escapeHtml(d.title)}</strong> — ${escapeHtml(d.description)}<br>
      <a href="${d.url}" target="_blank" rel="noopener">${d.url}</a>
    </div>
  </div>`
    )
    .join('\n\n');
  return `\n<section>\n  <h2>Read the Primary Sources</h2>\n\n  <p>Every claim in this tutorial is backed by one of these documents. When something does not work as expected, the spec is your ground truth.</p>\n\n${cards}\n\n</section>\n`;
}

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

let patched = 0;
let skipped = 0;
for (const dir of MODULE_DIRS) {
  const num = moduleNumFromDir(dir);
  if (num <= 2) {
    skipped++;
    continue; // modules 1-2 already have real spec-ref links
  }
  const tutorialPath = join(courseRoot, dir, 'tutorial.html');
  if (!existsSync(tutorialPath)) {
    console.warn(`  ! no tutorial.html for ${dir}, skipping`);
    continue;
  }
  let html = readFileSync(tutorialPath, 'utf8');

  if (html.includes('gen-spec-ref') || html.includes('Read the Primary Sources')) {
    skipped++;
    continue; // already patched or already has a real sources section
  }

  const section = buildSpecRefSection(num);
  if (!section) {
    console.warn(`  ! no docs entry for module ${num}, skipping tutorial.html patch`);
    continue;
  }

  if (!html.includes('</style>')) {
    console.warn(`  ! ${dir}/tutorial.html has no </style>, skipping CSS injection`);
  } else {
    html = html.replace('</style>', `${SPEC_REF_CSS}  </style>`);
  }

  if (!html.includes('</body>')) {
    console.warn(`  ! ${dir}/tutorial.html has no </body>, skipping section injection`);
  } else {
    html = html.replace('</body>', `${section}\n</body>`);
  }

  writeFileSync(tutorialPath, html, 'utf8');
  patched++;
}

console.log(`Patched ${patched} tutorial.html files, skipped ${skipped}.`);
